FLearningg/Flearning_FE

FrontEnd/src/components/common/Card/Card.css, FrontEnd/src/components/common/Card/Card.js, FrontEnd/src/components/common/Card/PopupCard.js
=> [FLN-47[Duc][UI] Fix PopupCard Problem #24.05.2025

FrontEnd/src/components/common/Card/Card.css
=> [HOTFIX][Duc][UI][PopupCard] Fix card on homepage # 25.5.2025

FrontEnd/package.json, FrontEnd/src/assets/AdminDashboard/AdminDashboard.css, FrontEnd/src/components/AdminDashboard/AdminDashboard.jsx
=> [UI][Feat] Add Admin Dashboard 

FrontEnd/src/assets/AdminEarning/AdminEarning.css, FrontEnd/src/components/AdminEarning/AdminEarning.jsx, FrontEnd/src/components/AdminHeaderAndSidebar/FinalHeaderAndSidebar.jsx, FrontEnd/src/components/AdminHeaderAndSidebar/HeaderMsg.jsx
=> [UI][Feat][fix] Add admin earning, update dynamic title header and fix responsive sidebar 

FrontEnd/src/assets/WatchCourse/CourseContents.css, FrontEnd/src/assets/WatchCourse/CourseHeader.css, FrontEnd/src/assets/WatchCourse/CourseInfo.css, FrontEnd/src/assets/WatchCourse/CourseTabs.css, FrontEnd/src/assets/WatchCourse/ReviewModal.css, FrontEnd/src/assets/WatchCourse/VideoPlayer.css, FrontEnd/src/assets/WatchCourse/WatchCourse.css, FrontEnd/src/components/WatchCourse/CourseContents.jsx, FrontEnd/src/components/WatchCourse/CourseHeader.jsx, FrontEnd/src/components/WatchCourse/CourseInfo.jsx, FrontEnd/src/components/WatchCourse/ReviewModal.jsx, FrontEnd/src/components/WatchCourse/VideoPlayer.jsx, FrontEnd/src/components/WatchCourse/WatchCourse.jsx
=> [FLN-29][FLN-30][Duc][Feat][UI] Add WatchCourse + Review #01.06.2025

FrontEnd/src/components/common/search/DropdownList/DropdownList.js, FrontEnd/src/components/common/search/DropdownList/DropdownList.module.css, FrontEnd/src/components/header/Header.jsx, FrontEnd/src/components/header/MobileHeader.jsx, FrontEnd/src/components/header/SearchBar.jsx
=> [Fix][UI][FLN-50_Fix-Header] Fix missing dropdown seach results.

FrontEnd/src/components/common/search/SearchBox/SearchBox.js, FrontEnd/src/components/common/search/SearchBox/SearchBox.module.css
=> [FLN-52][Dat][UI][Enhancement] No Results Found Search Box UI Enhancement 

FrontEnd/src/components/AdminEarning/AdminEarning.jsx, FrontEnd/src/routes/adminRoutes.jsx
=> [Dat][UI] Add Charts in AdminEarning UI

FrontEnd/src/assets/AdminDiscount/AdminDiscount.css, FrontEnd/src/components/AdminDiscount/AdminDiscount.jsx, FrontEnd/src/components/AdminHeaderAndSidebar/Sidebar.jsx, FrontEnd/src/routes/adminRoutes.jsx, FrontEnd/src/routes/mainRoutes.jsx, FrontEnd/src/routes/profileRoutes.jsx
=> [FLN-32][UI] Add Admin Discount

FrontEnd/src/assets/CRUDCourseAndLesson/CourseForm.css, FrontEnd/src/assets/CRUDCourseAndLesson/CoursePublish.css, FrontEnd/src/components/AdminHeaderAndSidebar/FinalHeaderAndSidebar.jsx, FrontEnd/src/components/CRUDCourseAndLesson/CourseCurriculum.jsx, FrontEnd/src/components/CRUDCourseAndLesson/CourseFormAdvance.jsx, FrontEnd/src/components/CRUDCourseAndLesson/CoursePublish.jsx, FrontEnd/src/routes/adminRoutes.jsx
=> [FLN-44][UI][Feat][Fix] Add Course Publish, fix title 

FrontEnd/src/assets/AdminMyCourse/AdminMyCourse.css, FrontEnd/src/components/AdminMyCourse/AdminMyCourse.jsx
=> [FLN-38][Feat][UI] Add Charts in Admin Course UI 

FrontEnd/src/assets/StudentCartPage/StudentCart.css, FrontEnd/src/components/CourseList/ProfileSection.jsx, FrontEnd/src/components/StudentCartPage/CartPage.jsx, FrontEnd/src/components/StudentCartPage/CartPagePagination.jsx, FrontEnd/src/components/header/HeaderRight.jsx, FrontEnd/src/components/header/NavigationBar.jsx, FrontEnd/src/routes/profileRoutes.jsx
=> [FLN-60][UI][Feat] Add shoppingcart page, fix wishlist container

FrontEnd/src/components/ShoppingCart/CheckoutPage.jsx
=> [UI][feat] Add checkout shopping cart page

COMMITS_PULLREQUEST_RULES.md
Thay đổi cập nhật file rule commit và tạo PR
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-76
---
=> [FLN-76][Hoang][DOCS] Update Rule PR and Commit [18.06.2025]

FrontEnd/src/components/CourseDetails/CourseDescription.jsx, FrontEnd/src/components/CourseDetails/CourseHeader.jsx, FrontEnd/src/components/CourseDetails/CourseRating.jsx, FrontEnd/src/components/CourseDetails/Curriculum.jsx, FrontEnd/src/components/CourseDetails/PricingCard.jsx, FrontEnd/src/components/CourseDetails/SingleCourse.jsx, FrontEnd/src/components/CourseDetails/StudentFeedback.jsx
=> [UI][feat] Add SingleCourse page and its components

FrontEnd/src/assets/homepage/TopCategory.css, FrontEnd/src/components/HomePage/Advertisement.jsx, FrontEnd/src/components/HomePage/BestSellingCourse.jsx, FrontEnd/src/components/HomePage/RecentlyAddedCourse.jsx, FrontEnd/src/components/HomePage/TopCategory.jsx, FrontEnd/src/components/HomePage/TopCategoryCard.jsx
=> [UI][Enhancement] Tách thành component nhận data từ array để hiển thị top category, chỉnh sửa lại css của bestSelling và Recently course

FrontEnd/src/assets/PurchaseHistory/PurchaseHistory.css, FrontEnd/src/components/CourseList/CourseList.jsx, FrontEnd/src/components/CourseList/ProfileSection.jsx, FrontEnd/src/components/ProfileSetting/ProfileSetting.jsx, FrontEnd/src/components/PurchaseHistory/PurchaseHistory.jsx, FrontEnd/src/components/StudentDashboard/StudentDashboard.jsx, FrontEnd/src/components/header/HeaderRight.jsx, FrontEnd/src/services/profileService.js
**Overview**
Tích hợp API cho phần settings, lịch sử mua và course đã tham gia
**Checklists**
=> [FLN-65][UI] Implement API for Profile Setting + Purchase History + Enrolled Course

FrontEnd/src/components/ProtectedRoute/ProtectedRoute.jsx, FrontEnd/src/components/ProtectedRoute/RoleBasedRoute.jsx, FrontEnd/src/routes/index.jsx
=> [Feat] Add Rolebased routes UI 

FrontEnd/package.json, FrontEnd/src/assets/CourseList/ProfileSection.css, FrontEnd/src/assets/StudentMsg/ChatInterface.css, FrontEnd/src/assets/StudentMsg/StudentMsgGlobal.css, FrontEnd/src/components/CRUDCourseAndLesson/CourseCurriculum.jsx, FrontEnd/src/components/CRUDCourseAndLesson/CourseFormAdvance.jsx, FrontEnd/src/components/CRUDCourseAndLesson/CourseWizard.jsx, FrontEnd/src/components/StudentMessage/ChatInterface.jsx, FrontEnd/src/components/StudentMessage/ComposeModal.jsx, FrontEnd/src/components/StudentMessage/StudentMessage.jsx, FrontEnd/src/hooks/useChat.js, FrontEnd/src/routes/adminRoutes.jsx, FrontEnd/src/services/chatService.js, FrontEnd/src/services/userService.js, FrontEnd/src/utils/socket.js
- Apply API cho message/chatting
- Loại bỏ bớt code thừa
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-67
---
=> [feat][refactor][FLN-67][Hoang][UI] Apply API to message/chatting

FrontEnd/src/assets/ProfileSetting/ProfileSetting.css, FrontEnd/src/components/CourseList/ProfileSection.jsx, FrontEnd/src/components/ProfileSetting/ProfileSetting.jsx
**Overview**
Chỉnh sửa cơ chế fetch ảnh mượt mà hơn.
**Checklists**
**EVD**
=> [FLN-79][UI] Update Fetching Profile Image

FrontEnd/src/assets/AdminDiscount/AdminDiscount.css, FrontEnd/src/components/AdminDiscount/AdminDiscount.jsx, FrontEnd/src/services/discountService.js
**Overview**
Thêm API CRUD Discount vào UI
**Checklists**
=> [FLN-71][UI] Implement CRUD Discount API

FrontEnd/src/pages/MainPage/ErrorPage.jsx, FrontEnd/src/pages/MainPage/FaqsPage.jsx, FrontEnd/src/routes/index.jsx
=> [FLN-35][UI] Update ErrorPage & Faqs 

FrontEnd/src/assets/header/header.css, FrontEnd/src/components/header/HeaderRight.jsx, FrontEnd/src/components/header/Notification.jsx, FrontEnd/src/components/header/WishList.jsx
**Overview**
Thay đổi sử dụng dropdown thuần để hiển thị notification và wishlist (luôn căn phải so với button)
Thay đổi className:
dropdown-menu-fixed-right (css thuần) --> dropdown-menu-end (bootstrap)
Vì notification dropdown luôn căn phải nên sẽ bị tràn ra màn hinh khi responsive nên sẽ ẩn đi khi < 576px
**Checklists**
**EVD**
=> [Fix][FLN-87] Sửa lại css và format code, comment code thừa

FrontEnd/src/services/authService.js
=> Refactor authService for improved token refresh handling

FrontEnd/src/App.js, FrontEnd/src/components/AdminHeaderAndSidebar/FinalHeaderAndSidebar.jsx, FrontEnd/src/components/AdminHeaderAndSidebar/Sidebar.jsx, FrontEnd/src/components/common/ScrollToTop.jsx, FrontEnd/src/components/header/LogoHeader.jsx, FrontEnd/src/index.js, FrontEnd/src/routes/index.jsx
- Auto scroll khi chuyển trang
- Bỏ bớt console log
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-94
---
=> [FLN-94][Hoang][UI] Fix bug auto scroll to top [09.07.2025]

FrontEnd/src/components/HomePage/BestSellingCourse.jsx, FrontEnd/src/components/HomePage/RecentlyAddedCourse.jsx
**Overview**
+ Sửa lại giá làm tròn 2 chữ số thập phân
**Checklists**
**Jira**
https://flearning.atlassian.net/browse/FLN-96
**EVD**
=> [FLN-96][UI][Fix] Fix price in bestSelling and recentlyAddedCourse at homepage

FrontEnd/src/components/CourseDetails/PricingCard.jsx
**Overview**
+ Ẩn nút Buy now khi người dùng đã enroll (đã mua)
**Checklists**
**Jira**
https://flearning.atlassian.net/browse/FLN-96
**EVD**
=> [FLN-96][UI][Fix] Ẩn nút Buy now khi người dùng đã enroll (đã mua)

FrontEnd/src/assets/StudentMsg/StudentMsgGlobal.css, FrontEnd/src/components/StudentCartPage/CartPage.jsx, FrontEnd/src/components/StudentMessage/ChatInterface.jsx, FrontEnd/src/components/StudentWishList/WishListPage.jsx
- cập nhật UX cho wishlist và cart
- cập nhật UI cho chat
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-95
---
=> [enhencement][FE] Update UX and UI

FrontEnd/src/assets/AdminDashboard/AdminDashboard.css, FrontEnd/src/assets/AdminEarning/AdminEarning.css, FrontEnd/src/assets/AdminManageUser/AdminManageUser.css, FrontEnd/src/components/AdminDashboard/AdminDashboard.jsx, FrontEnd/src/components/AdminEarning/AdminEarning.jsx, FrontEnd/src/components/AdminManageUser/AdminManageUser.jsx, FrontEnd/src/components/CRUDCourseAndLesson/CourseFormAdvance.jsx, FrontEnd/src/components/header/HeaderRight.jsx
- Thêm loading cho trang admin
- Thêm button navigate tới trang admin ở header home
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-102
---
=> [enhencement][fix] Enhencement UI and UX 

FrontEnd/src/assets/WatchCourse/CourseContents.css, FrontEnd/src/assets/WatchCourse/CourseHeader.css, FrontEnd/src/assets/WatchCourse/CourseInfo.css, FrontEnd/src/components/CourseDetails/PricingCard.jsx, FrontEnd/src/components/CourseList/CourseCard.jsx, FrontEnd/src/components/CourseList/CourseList.jsx, FrontEnd/src/components/StudentDashboard/StudentDashboard.jsx, FrontEnd/src/components/WatchCourse/CourseContents.jsx, FrontEnd/src/components/WatchCourse/CourseHeader.jsx, FrontEnd/src/components/WatchCourse/CourseInfo.jsx, FrontEnd/src/components/WatchCourse/VideoPlayer.jsx, FrontEnd/src/components/WatchCourse/WatchCourse.jsx, FrontEnd/src/routes/mainRoutes.jsx, FrontEnd/src/services/watchCourseService.js
**Overview**
- Cập nhập màn hình WatchCourse để fetch data
- Cập nhập các route dẫn tới màn WatchCourse
**Checklists**
=> [FLN-103][UI] Update WatchCourse to fetch data

FrontEnd/src/components/CourseList/CourseList.jsx, FrontEnd/src/components/StudentDashboard/StudentDashboard.jsx, FrontEnd/src/components/WatchCourse/CourseHeader.jsx, FrontEnd/src/components/WatchCourse/CourseInfo.jsx, FrontEnd/src/components/WatchCourse/WatchCourse.jsx, FrontEnd/src/services/feedbackService.js
**Overview**
- Apply API để tính rate trung bình của từng course
**Checklists**
=> [FLN][UI] Apply API to calculate average rating for course

FrontEnd/src/components/CourseDetails/CourseHeader.jsx, FrontEnd/src/components/CourseDetails/PricingCard.jsx, FrontEnd/src/components/CourseDetails/SingleCourse.jsx, FrontEnd/src/components/ShoppingCart/CheckoutPage.jsx
Overview:
+ Fix breadcumb and payment content
=> [FLN-108][Thien][UI] Fix breadcumb and payment content

FrontEnd/src/assets/WatchCourse/CourseContents.css, FrontEnd/src/assets/WatchCourse/QuizContent.css, FrontEnd/src/assets/WatchCourse/WatchCourse.css, FrontEnd/src/components/WatchCourse/CourseContents.jsx, FrontEnd/src/components/WatchCourse/CourseInfo.jsx, FrontEnd/src/components/WatchCourse/QuizContent.jsx, FrontEnd/src/components/WatchCourse/WatchCourse.jsx
**Overview**
- Thêm giao diện làm Quiz
**Checklists**
**EVD**
=> [FLN-128][Duc][UI] Add Do Quiz UI
